### ISSUE TITLE
Question regarding the marking scheme

### ISSUE THREAD

**Issue by afzalariffinZ** [TayQiXiang/WIA1002GroupAssignment#1]
For the first pathway (full stack application) in the assignment, does an android studio stack consisting of java, xml and sql/mongoDB count for the 4 marks instead of using react and springboot?

**Comment by TayQiXiang** [comment]
Ok, you can use android studio. 
Please package your application so that it can be easily tested. 
Also, if you are using an emulator, please provide exact steps to replicate your environment and a detail tutorial on how to start your application and how to access your database.
